select * from customer limit 20

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue 
from customer
group by gender 

--Q2. Which customers used a discount but still spent more than 
--the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount)
    FROM customer
);

--Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    AVG(review_rating) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

--Q4. Compare the average purchase amounts between Standard and 
--Express Shipping.
SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and 
--total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

--Q6. Which 5 products have the highest percentage of purchases 
--with discounts applied?
SELECT
    item_purchased,
    100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) AS discount_percentage
FROM customer
GROUP BY item_purchased
HAVING COUNT(*) > 0
ORDER BY discount_percentage DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their 
--total number of previous purchases, and show the count of each segment.
SELECT
    CASE
        WHEN previous_purchases <= 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Returning'
        WHEN previous_purchases > 5 THEN 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY
    CASE
        WHEN previous_purchases <= 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Returning'
        WHEN previous_purchases > 5 THEN 'Loyal'
    END;

--Q8. What are the top 3 most purchased products within each category?
WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    category,
    item_purchased,
    total_purchases
FROM product_counts
WHERE rn <= 3
ORDER BY category, total_purchases DESC;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) 
--also likely to subscribe?
SELECT
    subscription_status,
    COUNT(*) AS customer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?
SELECT
    CASE
        WHEN age < 25 THEN 'Under 25'
        WHEN age BETWEEN 25 AND 34 THEN '25-34'
        WHEN age BETWEEN 35 AND 44 THEN '35-44'
        WHEN age BETWEEN 45 AND 54 THEN '45-54'
        ELSE '55+'
    END AS age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY
    CASE
        WHEN age < 25 THEN 'Under 25'
        WHEN age BETWEEN 25 AND 34 THEN '25-34'
        WHEN age BETWEEN 35 AND 44 THEN '35-44'
        WHEN age BETWEEN 45 AND 54 THEN '45-54'
        ELSE '55+'
    END
ORDER BY total_revenue DESC;
